name: Build Expo App

on:
  workflow_dispatch:
    branches: [release-android]

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to your Expo account."
            exit 1
          fi
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: ./RecurRent
        run: npm install

      - name: Build AAB file
        working-directory: ./RecurRent
        run: eas build --platform android --non-interactive --clear-cache

      - name: Get build URL
        working-directory: ./RecurRent
        run: eas build:list --limit 1 --json --non-interactive --platform android | jq -r '.[0].artifacts.buildUrl'

      - name: Store AAB url in env variable
        working-directory: ./RecurRent
        run: |
          echo "AAB_URL=$(eas build:list --limit 1 --json --non-interactive --platform android | jq -r '.[0].artifacts.buildUrl')" >> $GITHUB_ENV

      - name: Download AAB file
        uses: suisei-cn/actions-download-file@v1
        id: downloadfile
        with:
          url: 'Downloading AAB from [this](${{ env.AAB_URL }})'
          target: public/
          auto-match: true
      
      - name: LIST DIR
        run: ls -R

      - uses: thedoctor0/zip-release@master
        with:
          path: public/
          filename: RecurRent-app.zip

      - name: Create Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}

      - name: Upload Release Asset to Github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./RecurRent-app.zip
          asset_name: RecurRent-app-v${{ github.run_number }}.zip
          asset_content_type: application/zip

  delete-release:
    runs-on: ubuntu-latest
    needs: update
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: sahil-randhawa/RecurRent
          keep_latest: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
