name: Test Workflow

on:
  workflow_dispatch:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
    - name: Install Buildah                                                                          
      run: |
        if [ -x "$(command -v apt-get)" ]; then                                                     
            sudo apt-get update                                                                       
            sudo apt-get install -y buildah                                                           
          elif [ -x "$(command -v dnf)" ]; then                                                       
            sudo dnf install -y buildah                                                               
          elif [ -x "$(command -v yum)" ]; then                                                       
            sudo yum install -y buildah                                                               
          else                                                                                        
            echo "Unsupported package manager. Cannot install buildah."                               
            exit 1                                                                                    
          fi 
    - name: Check env
      id: env
      shell: bash
      run: env
    - name: Install git
      id: install_git
      shell: bash
      run: |
          sudo apt update && sudo apt install git -y
    - uses: actions/checkout@main
      name: Checkout current branch
      with:
       fetch-depth: 0

    - name: LIST DIR
      run: |
        ls -la

    - name: check events
      id: check_event
      shell: bash
      run: |
        #Checking for event type
        echo "github event is ${{ github.event_name }}"
